# Exclude some folders & files
exclude: [_*, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Gem plugins
plugins: [jekyll-tidy, jekyll-sitemap, jekyll-seo-tag]

# Compress CSS
sass:
    style: compressed

# Set port
port: 69

# Enable local network access
host: 0.0.0.0